# Generated by Django 5.1.2 on 2024-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('produccion_leche_anual', models.FloatField()),
                ('enfermedad', models.BooleanField(default=False)),
                ('problemas_reproductivos', models.BooleanField(default=False)),
                ('resistencia_enfermedades', models.IntegerField()),
                ('historial_reproductivo_saludable', models.BooleanField(default=False)),
                ('familiares', models.JSONField(default=list)),
            ],
        ),
    ]
