# Generated by Django 5.1.2 on 2024-11-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_optimizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaca',
            name='historial_reproductivo_saludable',
        ),
        migrations.RemoveField(
            model_name='vaca',
            name='resistencia_enfermedades',
        ),
    ]
